on:
  push:
    paths-ignore:
      - 'terraform/**'
    branches:
      - niraj-branch

env:
  AWS_REGION: eu-west-2
  ECR_REPO_SERVICE1: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com/service1
  ECR_REPO_SERVICE2: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com/service2
  ECS_CLUSTER: dev-ecs-cluster
  ECS_SERVICE1: dev-ecs-cluster-service1
  ECS_SERVICE2: dev-ecs-cluster-service2
  
permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate markdown file
        run: |
          echo "# PR Summary" > pr-summary.md
          echo "" >> pr-summary.md
          echo "_ **Title:** ${{ github.event.pull_request.title }}" >> pr-summary.md
          echo "_ **Author:** ${{ github.event.pull_request.user.login }}" >> pr-summary.md
          echo "_ **Branch:** ${{ github.event.pull_request.head.ref }}" >> pr-summary.md
          echo "_ **Base Branch:** ${{ github.event.pull_request.base.ref }}" >> pr-summary.md
          echo "_ **PR Number:** ${{ github.event.pull_request.number }}" >> pr-summary.md
          echo "" >> pr-summary.md
          echo "## Changes Summary" >> pr-summary.md
          echo "${{ github.event.pull_request.body }}" >> pr-summary.md

      - name: Extract branch name
        id: extract-branch
        run: |
          # Extract the branch name from github.ref (e.g., refs/heads/niraj-branch)
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          echo "Branch name: $BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Commit markdown file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add pr-summary.md
          git commit -m "add pr summary markdown"
          git push https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git HEAD:$BRANCH_NAME

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
         
